### ISSUE TITLE
When is an agent considered well trained?

### ISSUE THREAD

**Issue by Davinho10** [Farama-Foundation/HighwayEnv#436]
I have trained my agent on the highway environment with DQN and was wondering if there is a specific point when the agent is classified as well trainend. Maybe if it reaches a specific length for an episode or if the average reward of a 100 episodes exceeds a specific value.

Thanks in regards

**Comment by eleurent** [comment]
Hi, 
No, I wouldn't say there is an established criterion to consider the tasks as solved vs not, beside that the higher the reward the better :) 

And even then, there is typically an efficiency vs safety tradeoff which is not directly addressed in the reward function, so a 'safe-but-inefficient policy' could have the same expected reward as a 'risky-but-fast' one

We can of course come up with criteria like a maximum collision rate, etc., but nothing universal, in the end it depends on your exact application.

**Comment by Davinho10** [comment]
Thank you for the explanation
