### ISSUE TITLE
Get dynamical details of the vehicle

### ISSUE THREAD

**Issue by Ethanjoo** [Farama-Foundation/HighwayEnv#440]
Hi, I'm now trying to work on some riding comfort studies, which means more dynamical parameters of the vehicle is needed. I have set dynamical to True in the env configuration. Is there any way that I'm able to obtain the detailed dynamical parameters of the ego vehicle? For example, the lateral acceleration?

**Comment by eleurent** [comment]
The current version you only get positions and velocities in the observation/info fields unfortunately.
We could add the accelerations there, but alternatively you can access them directly with `env.vehicle` For details on what information is available, see 

https://github.com/Farama-Foundation/HighwayEnv/blob/2523ea2aecb6ef7399e2c1df573c461e44e1125f/highway_env/vehicle/dynamics.py#L30

For example, the index 4 of env.vehicle.derivative will give you the derivative of lateral speed (which I don't think is equal to the lateral acceleration, you may have to do additional computations to recover it. Point is, you have access to all the internal simulator state).

**Comment by Ethanjoo** [comment]
Thanks! I will check this out!
