### ISSUE TITLE
add editable length and width attributes to road objects

### ISSUE THREAD

**Issue by EvergrowHook** [Farama-Foundation/HighwayEnv#446]
Hi, I'm now working on path planning in parking env, and I have to deal with many obstacles on the road.
Currently all road objects have the same size if they belong to the same category, which I found annoyed because obstacles usually have different sizes. I think it is better to change the constant LENGTH and WIDTH to attributes that can be initialized seperately.
Many thanks.

**Comment by eleurent** [comment]
For now, you can override these class properties with instance properties by doing

```
obstacle = Obstacle(...)
obstacle.WIDTH = ...
obstacle.LENGTH = ...
```

But I agree that these should probably be instance properties in the first place.

**Comment by EvergrowHook** [comment]
I read the lastest code of parking env and understand it.
Thanks for your help.
