### ISSUE TITLE
Online document is unavailable now (18/04/23)

### ISSUE THREAD

**Issue by AlxZn** [Farama-Foundation/HighwayEnv#453]
I hope this message finds you well. I found the https://highway-env.readthedocs.io/en/latest/ is unavailable now, I'd appreciate if you can provide the offline PDF document of the HighwayEnv. I am very interested in learning more about this software and I believe that having access to an offline copy of the documentation would greatly assist me in my efforts to understand it better.

**Comment by aleksa-sukovic** [comment]
The docs have been moved [here](https://farama-foundation.github.io/HighwayEnv/).
