### ISSUE TITLE
Car is crashing in 99% of episodes

### ISSUE THREAD

**Issue by Davinho10** [Farama-Foundation/HighwayEnv#462]
https://colab.research.google.com/drive/1EDCb9CLFUmNdV4gbdSDbM-BTpokwLvb6?usp=sharing
The provided link is my code with which I ran the agent on the environment. I cant find the mistake I made which led to these poor results

**Comment by eleurent** [comment]
Hi, sorry for the late reply.
Maybe it is because the exploration fraction is still quite high in the end (0.58)? You should be able to get a better mean reward for this task, around 25.0 at least
