### ISSUE TITLE
Clearing up some ambiguities

### ISSUE THREAD

**Issue by HodaHo** [Farama-Foundation/HighwayEnv#471]
Thank you for your great work,

After reading the document, I found some ambiguities in the meta-discrete action examples:
1- Specifically, what is the purpose and role of the reinforcement algorithm in these examples of self-driving cars? Is determining the speed (V) among a number of desirable speeds given V_des=[] as an action to the car?
2- If yes, is this choice applied directly to the car or is it first converted to acceleration using the low level control? In other words, is my understanding correct that in a relationship a=k(V-Vr), Vr is determined by using reinforcement and among a certain discrete choice?
3- Why is discrete acceleration not simply determined by using reinforcement to be applied?

**Comment by eleurent** [comment]
Hi,
1. Yes, that is correct. (there are also actions to change lanes)
2. Yes, that is also correct.
3. It is also possible to control the acceleration direclty, it's just a different action space that you can configure: Either `ContinuousAction` or `DiscreteAction` (But not DiscreteMetaAction). See the documentation.
