### ISSUE TITLE
some kinematics observation values return zero

### ISSUE THREAD

**Issue by mehmetozturan** [Farama-Foundation/HighwayEnv#476]
i try to kinematics observation on racetrack environment but ``cos_d`` and ``sin_d`` values return zero how to fix this? also i want value of "done" to be true when the vehicle is off the road, so how to setup this? any help?

**Comment by eleurent** [comment]
> i try to kinematics observation on racetrack environment but cos_d and sin_d values return zero how to fix this

These features should not be included by default. For any vehicle, they give the direction from its current position to its destination, if one exists. But destinations are used for route planning, and this doesnt apply to the racetrack env (continuous control task, single route), so its expected.

> also i want value of "done" to be true when the vehicle is off the road, so how to setup this? any help?

You can edit the termination condition here
https://github.com/Farama-Foundation/HighwayEnv/blob/a83801baace59d01c7b56cf2633db8c5ebb13003/highway_env/envs/racetrack_env.py#L74

and add `or not self.vehicle.on_road`

**Comment by mehmetozturan** [comment]
Thanks a lot
