### ISSUE TITLE
Unable to add more than 5 (other) vehicles to parking-v0 environment (and they overlap the goal spot sometimes).

### ISSUE THREAD

**Issue by mmarfat** [Farama-Foundation/HighwayEnv#478]
I'm trying to add 10 vehicles to the default parking-v0 environment. However, for some reason there's always only 5 vehicles even though there's plenty of space. Here's the code, even though I'm certain it's correct:
```
env = gym.make('parking-v0', render_mode='rgb_array')
env.config['vehicles_count'] = 10
```

Example of the issue:

https://github.com/Farama-Foundation/HighwayEnv/assets/77555970/447c72ed-bf5b-4021-b21c-d913414c1a16

I'm guessing the issue is in the `_create_vehicles()` function but I'm not 100% certain so I'd rather have a confirmation/fix rather than dabble myself.

**Comment by moneypi** [comment]
May I ask how do  you custom you deep learning network to train the custom env?
