### ISSUE TITLE
Try to adjust the speed of controlled vehicle in the parking-v0 env

### ISSUE THREAD

**Issue by ZhangyuHuang** [Farama-Foundation/HighwayEnv#479]
Thanks for your excellent work!
Though the success rate reached 0.96, I found in the failed situation, most of these situations are vehicle crushed within a high speed. So I try to adjust the speed of vehicle.
And in the `_create_vehicles`  function of `parking_env.py,` vehicle can be changed by`vehicle = self.action_type.vehicle_class(self.road, [i*20, 0], 2*np.pi*self.np_random.uniform(), 0)`
So I go to `vehicle_class` : the `kinematics.py`, there are some of Speed can be changed:
`DEFAULT_INITIAL_SPEEDS = [23, 25]`
`    """ Range for random initial speeds [m/s] """`
`    MAX_SPEED = 40.`
`    """ Maximum reachable speed [m/s] """`
`    MIN_SPEED = -5.`
`    """ Minimum reachable speed [m/s] """`
I try to set DEFAULT_INITIAL_SPEEDS = [3,5] and MAX_SPEED = 5, and the speed of vehicle is also very high. 
I am not sure my work is correct or not, could you give me some advice? Thanks a lot.

**Comment by eleurent** [comment]
Hi, 
`DEFAULT_INITIAL_SPEEDS` is only used in some environments for randomly created vehicles, and wont have any effect here. Setting `MAX_SPEED` should work though, but don't forget to also set `MIN_SPEED`. This should work, for example:
```
from highway_env.vehicle.kinematics import Vehicle
Vehicle.MAX_SPEED = 3
Vehicle.MIN_SPEED = -3
```

**Comment by ZhangyuHuang** [comment]
That works! Thank u😊
