### ISSUE TITLE
How does the ego vehicle controlled by reinforcement learning perceive obstacles?

### ISSUE THREAD

**Issue by seominseok00** [Farama-Foundation/HighwayEnv#480]
In the custom merge environment (with discrete meta-actions and kinematics observations) being trained using reinforcement learning, the IDMVehicle class, which represents vehicles other than the ego vehicle, detects and avoids obstacles through the [neighbor_vehicles method](https://github.com/Farama-Foundation/HighwayEnv/blob/master/highway_env/vehicle/behavior.py#L100) of the Road class. However, the MDPVehicle, which is controlled by reinforcement learning, does not invoke this method.

I was wondering if obstacle information is obtained through observations, so I looked into the KinematicObservation class. However, in the [observe method](https://github.com/Farama-Foundation/HighwayEnv/blob/master/highway_env/envs/common/observation.py#L203), only vehicle information is retrieved, and obstacle information is not obtained. How does the ego vehicle perceive obstacles then?

**Comment by eleurent** [comment]
Hi, this is a great point! Obstacles used to be defined as `Vehicle`s (with 0 speed) and thus be part of the KinematicsObservation. They were only later moved to a different class for disambiguation, and I didnt realise that would cause this issue.

Thank you for bringing this up, I will fix the KinematicsObservation such that it also includes obstacles.

**Comment by seominseok00** [comment]
Thank you. Please notify me once the issue is fixed.

**Comment by eleurent** [comment]
It should be fixed now, if you install the dev (head) version

**Comment by seominseok00** [comment]
If I understand correctly, you implemented the code so that if there are vehicles_count number of close vehicles, the obstacle information does not come through the observation. Is that correct?

With this implementation, even if there is an obstacle nearby, if there are vehicles_count number of vehicles nearby, no obstacle information is received at all. Instead of doing it this way, wouldn't it be better to receive both the vehicles and observation as input, sort them by distance, and then display the top vehicles_count?

Here is the code I have implemented

highway_env/road/road.py
Road class

```python
def close_objects_to(self, vehicle: 'kinematics.Vehicle', distance: float, count: Optional[int] = None,
                         see_behind: bool = True, sort: bool = True) -> object:
        vehicles = [v for v in self.vehicles
                    if np.linalg.norm(v.position - vehicle.position) < distance
                    and v is not vehicle
                    and (see_behind or -2 * vehicle.LENGTH < vehicle.lane_distance_to(v))]

        obstacles = [o for o in self.objects
                    if np.linalg.norm(o.position - vehicle.position) < distance
                    and -2 * vehicle.LENGTH < vehicle.lane_distance_to(o)]
        
        objects = vehicles + obstacles

        if sort:
            objects = sorted(objects, key=lambda o: abs(vehicle.lane_distance_to(o)))
        if count:
            objects = objects[:count]
        return objects
```

highway_env/envs/common/observation.py
KinematicObservation class

```python
def observe(self) -> np.ndarray:
        if not self.env.road:
            return np.zeros(self.space().shape)

        # Add ego-vehicle
        df = pd.DataFrame.from_records([self.observer_vehicle.to_dict()])
        # Add nearby traffic
        close_objects = self.env.road.close_objects_to(self.observer_vehicle,
                                                         self.env.PERCEPTION_DISTANCE,
                                                         count=self.vehicles_count - 1,
                                                         see_behind=self.see_behind,
                                                         sort=self.order == "sorted")
        
        close_obstacles = self.env.road.close_obstacles_to(self.observer_vehicle,
                                                         self.env.PERCEPTION_DISTANCE,
                                                         count=self.vehicles_count - 1,
                                                         sort=self.order == "sorted")
        print('close_obstacles')
        print(close_obstacles)
        print()
        
        if close_objects:
            origin = self.observer_vehicle if not self.absolute else None
            objects_df = pd.DataFrame.from_records(
                [o.to_dict(origin, observe_intentions=self.observe_intentions)
                 for o in close_objects[-self.vehicles_count + 1:]])
            df = pd.concat([df, objects_df], ignore_index=True)

        df = df[self.features]

        # Normalize and clip
        if self.normalize:
            df = self.normalize_obs(df)
        # Fill missing rows
        if df.shape[0] < self.vehicles_count:
            rows = np.zeros((self.vehicles_count - df.shape[0], len(self.features)))
            df = pd.concat([df, pd.DataFrame(data=rows, columns=self.features)], ignore_index=True)
        # Reorder
        df = df[self.features]
        obs = df.values.copy()
        if self.order == "shuffled":
            self.env.np_random.shuffle(obs[1:])
        # Flatten
        return obs.astype(self.space().dtype)
```
