### ISSUE TITLE
Error in Creation of New Custom Environment

### ISSUE THREAD

**Issue by Yuvraj-Dhepe** [Farama-Foundation/HighwayEnv#481]
Hello team, 
I am working on creation of a custom env, but before starting I wanted to just try to copy code from RaceTrack and see if I can create a same dummy env.

Following are the:
- Content in your_env.py file is same as the race circuit.py, since I was just trying to build it same just I named the class as YourEnv instead of RacetrackEnv
- Content from the highway_env/envs/__init__.py
```
from highway_env.envs.highway_env import *
from highway_env.envs.merge_env import *
from highway_env.envs.parking_env import *
from highway_env.envs.roundabout_env import *
from highway_env.envs.two_way_env import *
from highway_env.envs.intersection_env import *
from highway_env.envs.lane_keeping_env import *
from highway_env.envs.u_turn_env import *
from highway_env.envs.exit_env import *
from highway_env.envs.racetrack_env import *

from gymnasium.envs.registration import register # I added this line since it was not there by default

register(
    id='your-env-v0',
    entry_point='highway_env.envs:YourEnv',
)
```

However, after doing as guided on Make your env, page from **[user guide](http://highway-env.farama.org/make_your_own/)** 

I get the following error in jupyter notebook:
**Could you pls help me resolve it, so that I can create my environment.**

```
NameNotFound                              Traceback (most recent call last)
Cell In[23], line 1
----> 1 env = gym.make('your-env-v0')
      2 obs, info = env.reset()
      3 obs, reward, terminated, truncated, info = env.step(env.action_space.sample())

File ~/MSc_Life/Sem_two/uni_RL/venv/lib/python3.11/site-packages/gymnasium/envs/registration.py:740, in make(id, max_episode_steps, autoreset, apply_api_compatibility, disable_env_checker, **kwargs)
    737     assert isinstance(id, str)
    739     # The environment name can include an unloaded module in "module:env_name" style
--> 740     env_spec = _find_spec(id)
    742 assert isinstance(env_spec, EnvSpec)
    744 # Update the env spec kwargs with the `make` kwargs

File ~/MSc_Life/Sem_two/uni_RL/venv/lib/python3.11/site-packages/gymnasium/envs/registration.py:537, in _find_spec(env_id)
    531     logger.warn(
    532         f"Using the latest versioned environment `{new_env_id}` "
    533         f"instead of the unversioned environment `{env_name}`."
    534     )
    536 if env_spec is None:
--> 537     _check_version_exists(ns, name, version)
    538     raise error.Error(f"No registered env with id: {env_name}")
    540 return env_spec

File ~/MSc_Life/Sem_two/uni_RL/venv/lib/python3.11/site-packages/gymnasium/envs/registration.py:403, in _check_version_exists(ns, name, version)
    400 if get_env_id(ns, name, version) in registry:
    401     return
--> 403 _check_name_exists(ns, name)
    404 if version is None:
    405     return

File ~/MSc_Life/Sem_two/uni_RL/venv/lib/python3.11/site-packages/gymnasium/envs/registration.py:380, in _check_name_exists(ns, name)
    377 namespace_msg = f" in namespace {ns}" if ns else ""
    378 suggestion_msg = f" Did you mean: `{suggestion[0]}`?" if suggestion else ""
--> 380 raise error.NameNotFound(
    381     f"Environment `{name}` doesn't exist{namespace_msg}.{suggestion_msg}"
    382 )

NameNotFound: Environment `your-env` doesn't exist.
```

- **Also I tried to run my your_env.py file and __init__.py file from terminal, just in case they were not run by default,** but then I get the errors as follows
```
python3 ./envs/your_env.py                                             ─╯
Traceback (most recent call last):
  File "/home/yuvi_dh/MSc_Life/Sem_two/uni_RL/venv/lib/python3.11/site-packages/highway_env/./envs/your_env.py", line 380, in <module>
    from highway_env.envs.common.abstract import AbstractEnv
  File "/home/yuvi_dh/MSc_Life/Sem_two/uni_RL/venv/lib/python3.11/site-packages/highway_env/envs/highway_env.py", line 5, in <module>
    from highway_env import utils
ImportError: cannot import name 'utils' from partially initialized module 'highway_env' (most likely due to a circular import) (/home/yuvi_dh/MSc_Life/Sem_two/uni_RL/venv/lib/python3.11/site-packages/highway_env/envs/highway_env.py)
```

- **And if I put all the contents of the utils manually in the highway env I get the following error**
```
python3 ./envs/your_env.py                                             ─╯
Traceback (most recent call last):
  File "/home/yuvi_dh/MSc_Life/Sem_two/uni_RL/venv/lib/python3.11/site-packages/highway_env/./envs/your_env.py", line 380, in <module>
    from highway_env.envs.common.abstract import AbstractEnv
  File "/home/yuvi_dh/MSc_Life/Sem_two/uni_RL/venv/lib/python3.11/site-packages/highway_env/envs/highway_env.py", line 382, in <module>
    from highway_env.envs.common.abstract import AbstractEnv
ModuleNotFoundError: No module named 'highway_env.envs'; 'highway_env' is not a package
```

I am not sure, is it cause the folder names are making the terminal confused a bit... just a noob guess, but really would appreciate if someone can point me in the right direction.

**Comment by Yuvraj-Dhepe** [comment]
I got a fix @eleurent, sorry but I think though it might be a trivial solution to the problem, mentioning it in the documentation of the highway-env can help the users a bit more.

So here's how one of my team mate solved the error:
- Create the your_env.py file as per the [user-guide](http://highway-env.farama.org/make_your_own/)
- Inside ```highway_env/envs/__init__.py``` you need to import your_env as well by adding ```from highway_env.envs.your_env import *```
- Then add the register command as suggested in the [user-guide](http://highway-env.farama.org/make_your_own/) in this __init__.py file i.e.
```
register(
    id='your-env-v0',
    entry_point='highway_env.envs:YourEnv',
)
```

- Save the your_env.py and __init__.py file in folder ```highway_env/envs/```
- After this you need to run 

``` python
from highway_env.envs.your_env import * #This is how you resolve the error of your-env doesn't exist
import gymnasium as gym

env = gym.make('your-env-v0')
obs, info = env.reset()
obs, reward, terminated, truncated, info = env.step(env.action_space.sample())
env.render()
```

- This will solve the problem, but still I dont' get what is the problem of circular import when I simply run your_env.py file from ```highway_env/envs/``` folder maybe you can share the information

- Once again, maybe I misread or forgot to read this somewhere if it's in github repo or so, apologies for that n Thanks for making this awesome env 🙌

**Comment by eleurent** [comment]
Hi @Yuvraj-Dhepe 
I'm very sorry about that, the documentation was a bit outdated. The env registration process changed a bit when we moved from gym to gymnasium, and I forgot to update the docs.
I just fixed it, you can take a look if you want, but I'm glad you figured it out :)

**Comment by Yuvraj-Dhepe** [comment]
Hi @eleurent,
Thanks for fix.
I think now users will have a bit smoother experience.
