### ISSUE TITLE
action skip

### ISSUE THREAD

**Issue by Gricha1** [Farama-Foundation/HighwayEnv#486]
Thanks authors for the great job.

I have a problem with implementing action skip for the car on highway scenario. I use action = DiscreteMetaAction, but the agent change his decision really quick, so i need to slow down him. 
I have tried to change the tradeoff between policy freq and sim freq, it is not clear enough how does it work.

The documentation says: sim freq is the count of visualized frames for each dt = (1/policy_freq) time. So if i have policy_freq = 30 and  sim_freq = 30, then i will get 30 * 30 visualized frames for 1 second of simulation. But if we look at the code,     
https://github.com/Farama-Foundation/HighwayEnv/blob/master/highway_env/envs/common/abstract.py#L258C7-L258C7

249 line:
`frames = int(self.config["simulation_frequency"] // self.config["policy_frequency"])`
 `for frame in range(frames):`
        `self.road.step(1 / self.config["simulation_frequency"])`
       
we have frames = 1, and will create 30 visualized frames for 1 sec.

**Comment by eleurent** [comment]
Hi,

> The documentation says: sim freq is the count of visualized frames for each dt = (1/policy_freq) time

This is incorrect, I'm sorry if the documentation was misleading, can you please give me the reference of where you read that so I can fix it?

Each frames simulates a tilmestep dt = 1/simulation_frequency, and an action is taken by the agent every 1/policy_frequency time units, i.e. every simulation_frequency/policy_frequency frames.
If you have policy_freq = sim_frq = 30, then 1 second of simulation gives you 30 frames (and 30 decisions).
