### ISSUE TITLE
How do you create one-lane environment?

### ISSUE THREAD

**Issue by laurentfang** [Farama-Foundation/HighwayEnv#487]
I have created a one-lane environment (one lane in each opposite direction). I want to generate some random vehicles in both directions. How can I change the vehicles' moving direction? Is there any API that I can use?

**Comment by eleurent** [comment]
Hi, 
If you use the `IDMVehicle` class in your environment, they automatically follow the lane direction, so you would have to superimpose two lanes, one going from A --> B and the other B --> A.

If the road is straight, the alternative is to just spawn vehicles with the `Vehicle` class, which don't have any lane keeping control, so just set their heading to +np.pi and a positive initial speed.
