### ISSUE TITLE
Time between two states

### ISSUE THREAD

**Issue by favu100** [Farama-Foundation/HighwayEnv#489]
Thank you contributors for implementing the highway environment!

We have got a question regarding the time elapsed between two states/observations. Taking a closer look at the documentation, the time elapsed between two observations seems to be 50ms (target_update_interval=50) for highway-env-fast. Can you approve that my assumption is correct?

Furthermore, when using the standard version (without -fast), what is the time between two observations there?

Best regards,

Fabian

**Comment by eleurent** [comment]
No, that is not correct. 
I think you are referring to the ´target_update´ config in the DQN agent of my rl-agents? This refers to the number of sgd steps before the target network parameters are updated to the current network params. 

The time elapsed between two observations is 1/policy_frequency, where policy_frequency is configurable. 
On highway-fast-v0, it is equal to 1.0, so we receive an observation and take an action every 1.0 second. 

The maximum policy_frequency is simulation_frequency, which is 5.0 by default (0.2s per frame). It can also be configured and increased, which makes simulation more accurate but also slower.

**Comment by eleurent** [comment]
No, that is not correct. 
I think you are referring to the ´target_update´ config in the DQN agent of my rl-agents? This refers to the number of sgd steps before the target network parameters are updated to the current network params. 

The time elapsed between two observations is 1/policy_frequency, where policy_frequency is configurable. 
On highway-fast-v0, it is equal to 1.0, so we receive an observation and take an action every 1.0 second. 

The maximum policy_frequency is simulation_frequency, which is 5.0 by default (0.2s per frame). It can also be configured and increased, which makes simulation more accurate but also slower.

**Comment by eleurent** [comment]
Just saw your second question : the default simulation_frequency for the non-fast env is 15, ie 66ms between two frames (but still 1.0s between observations/actions if you don't change the policy frequency)

**Comment by favu100** [comment]
Ah okay, so there is a difference between "the time between two frames", and "the time between two observations"?
Referring to the observations, this would be 1 seconds?

**Comment by favu100** [comment]
Thank you very much!
