### ISSUE TITLE
Questions about environmental vehicle creation

### ISSUE THREAD

**Issue by zhangjianguo-max** [Farama-Foundation/HighwayEnv#490]
Hi, when I was creating the environment vehicle, I found that the ego-vehicle and the other vehicles created in the environment were all using the same length and width, which seemed different from the real world scene. So I want to set up some extra trucks and vans (which are different in length and width from ego-vehicles) in the environment vehicle, how should I set up.

**Comment by eleurent** [comment]
Hi,
After a vehicle is created in your environment's _create_vehicles(), you can edit its LENGTH and WIDTH as follows:

```
vehicle.LENGTH = 5.0
vehicle.WIDTH = 2.0
vehicle.diagonal = np.sqrt(vehicle.LENGTH**2 + vehicle.WIDTH**2
```

**Comment by zhangjianguo-max** [comment]
Thank you very much for your reply. Yes, I found the default Settings LENGTH = 5.0, WIDTH = 2.0 at kinematics.py, but I found that this resulted in the same length and width for all vehicles in the simulation. I want to set up 50 environment cars, including 40 (LENGTH = 5.0, WIDTH = 2.0), 10 (LENGTH = 10.0, WIDTH = 2.5), I would like to ask how I can achieve this setup.

**Comment by eleurent** [comment]
you shouldn't change the global (default) variables but go through each vehicle when they are created, and edit their attributes instead, as shown above
