### ISSUE TITLE
De-normalizing

### ISSUE THREAD

**Issue by favu100** [Farama-Foundation/HighwayEnv#494]
Hello,

I am currently using the highway environment in its default setting.
Assuming that I have normalized values:

x = 0.05 
y= 0.04 
vx = 0.75 
vy = 0.1

Now, I want to to compute the original values. How does the "de-normalizing" function look like?
I have also taken a look at https://highway-env.farama.org/observations/
Somehow, I have the feeling that the default range is not: [100, 100, 20, 20]
Or am I wrong?

**Comment by favu100** [comment]
As far as I understand, the following feature ranges are used:

"x": [-5.0 * Vehicle.MAX_SPEED, 5.0 * Vehicle.MAX_SPEED],
"y": [-AbstractLane.DEFAULT_WIDTH * len(side_lanes), AbstractLane.DEFAULT_WIDTH * len(side_lanes)],
"vx": [-2 * Vehicle.MAX_SPEED, 2 * Vehicle.MAX_SPEED],
"vy": [-2 * Vehicle.MAX_SPEED, 2 * Vehicle.MAX_SPEED]

As we have a MAX_SPEED of 40 m/s:
- The x coordinate needs to be multiplied by 5 * 40 = 200.
- The velocity in the x and y directions should be multiplied by 2 * 40 = 80.

As we have an AbstractLane.DEFAULT_WIDTH of 4.0 and we have 3 lanes: 
- The y coordinate should be multiplied by 4 * 3 = 12


Therefore the aforementioned values would be mapped to:

x = 10
y = 0.48
vx = 60
vy = 8

**Comment by eleurent** [comment]
Sorry for the late reply, yes you're right the example in the docs is not very clear, it was only meant as an example to show the computation for a given range "which gives for the range [100, 100, 20, 20]",

But this range is configurable, and if none is provided, a default one is computed dynamically based on other parameters (but this choice doesnt make sense for all scenes, in particular y which assumes horizontal lanes).

**Comment by favu100** [comment]
Okay, thank you very much!
