### ISSUE TITLE
racetrack-env numpy attribute error and working model

### ISSUE THREAD

**Issue by christophluther** [Farama-Foundation/HighwayEnv#495]
Hi, thanks for the great for on the highway env. However, I am using the racetrack-env and encountered a few issues:

i) AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint’. 

Using the sb3_racetrack_ppo.py script from your repo (https://github.com/Farama-Foundation/HighwayEnv/blob/master/scripts/sb3_racetracks_ppo.py), everything works fine for the default configuration. When setting “other_vehicles” = n for n>1, however, I encounterred the error above.

It is solved by replacing `_id = np_random.randint(len(self.graph[_from][_to]))` with `_id = np_random.integers(len(self.graph[_from][_to]))` in line 258 of highway_env/road/road.py, which is also suggested by https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html (cf. the Note: “new code should use the integers method ….)

Versions: Python 3.9.13, numpy 1.23.5, highway-env 1.8 (in this version it's still line 254 in road.py file)

(if this is a general issue, which I think it is, you may want to resolve it or I can create a pr)

ii) I have trouble finding a model that performs well in the environment. The example agent displayed in the Readme seems to be actively avoiding a crash. Is this agent trained with the sb3_racetrack_ppo.py script from your repo (https://github.com/Farama-Foundation/HighwayEnv/blob/master/scripts/sb3_racetracks_ppo.py)? Or did you use another model or other hyperparameters? Is there any pre-trained model available?

When I use sb3_racetrack_ppo.py to train an agent, I only occasionally observe similar behaviour (i.e. actively avoiding a crash by switching a lane) but most of the time the ego vehicle crashes into the other vehicle or does a very early lane switch (example of very early lane switch in video below) at the beginning of the episode (not an ad-hoc avoidance of a crash). Both of the latter scenarios lead to crashes on a more crowded track (”other_vehicles” > 1).

I used the same script and tried several alterations of hyperparameters (batch size, size of layers in policy and value function, epochs, lr, gamma) and environment configurations (mostly, target speeds, collision reward, lane centrering cost, action reward, no. of other vehicles), however, none of which seemed to improve performance. Especially and quite surprinsingly, increasing the number of other vehicles and decreasing collision reward (i.e. higher absolute value of the negative reward) did not mitigate the issue. 

I would appreciate any hint, idea or starting point for a working RL agent. A pre-trained model or similar to look into would help a lot too. If you are interested in any more detail in the hyperparameter search/search over configuration parameters, I am very happy to provide more info and/or share my code (since the search wasn't successful though, I spared it at this point).

iii) Lastly, what is the best way to alter the configurations of the environment but still be able to use make_vec_env from stable_baselines_3?
If I do env.configure("configuration dict"), do I have to register the newly configured env to call it with make_vec_env?

My workaround so far is changing the default env in the source code.

Very early lane change:
https://github.com/Farama-Foundation/HighwayEnv/assets/52353770/14628b78-b760-47e5-a82f-d5ef453fd24d

**Comment by eleurent** [comment]
Hi!

i) Thanks for letting me know, will fix.
ii)
> Is this agent trained with the sb3_racetrack_ppo.py script from your repo ?

Yes, I used SB3's PPO.

> Or did you use another model or other hyperparameters? Is there any pre-trained model available?

This is probably the same model / hyperparams, although I don't remember it precisely I don't think I changed anything. The trained model might still be somewhere on the computer I used for training, I'll take a look.

>  I only occasionally observe similar behaviour (i.e. actively avoiding a crash by switching a lane) but most of the time the ego vehicle crashes into the other vehicle or does a very early lane switch (example of very early lane switch in video below) at the beginning of the episode (not an ad-hoc avoidance of a crash). Both of the latter scenarios lead to crashes on a more crowded track (”other_vehicles” > 1).

Yes I think I observed similar behaviours: some early switches (which is fine, nothing in the reward is incentivising to stay on lane), some avoidances, and a few crashes.

I have to say that I didn't try too hard to get a perfect behaviour on that env, it was proposed by someone else in [this issue](https://github.com/eleurent/highway-env/issues/231), I only helped fixing a few issues, ran a test training run which gave decent results, and considered it satisfactory enough to ship it. I didn't try the things you did for instance, such as increasing the number of other vehicles.

> I would appreciate any hint, idea or starting point for a working RL agent. A pre-trained model or similar to look into would help a lot too. If you are interested in any more detail in the hyperparameter search/search over configuration parameters, I am very happy to provide more info and/or share my code (since the search wasn't successful though, I spared it at this point).

I think one of the most common limitation is the choice of observation space. Maybe the one I chose by default here is not sufficient to get a perfect performance, you may want to try e.g. with image-based observations and a CNN policy architecture. An observation / policy architecture pair that I generally found efficient at understanding interactions between vehicles and avoiding collisions is the Kinematics observation (one row per vehicle, with accurate relative coordinates as features) and a transformer-based architecture. This would also probably improve the collision avoidance capabilities here, but it would require including the lane information somehow (you could have an image/occupancy grid/cnn trunk for the lanes, a kinematics/transfomer trunk for the vehicles, and concatenate the two embeddings before an MLP head or something.

But yes, these driving problems are by no means trivial, and it is difficult to get a 100% succes performance with RL even for seemingly simple tasks.

> iii) Lastly, what is the best way to alter the configurations of the environment but still be able to use make_vec_env from stable_baselines_3?

make_vec_env can accept as input a [callable returning an env](https://github.com/DLR-RM/stable-baselines3/blob/f4ec0f6afa1a23b0e0b746174cd0074471cc0b89/stable_baselines3/common/env_util.py#L40), so you should be able to use something like

```
make_env = lambda: gym.make('racetrack-v0', config={...})
make_vec_env(make_env, n_envs=8)
```

**Comment by christophluther** [comment]
Thanks for the comprehensive response. If I find a better model, I'll post it here.
