### ISSUE TITLE
Maximum deceleration and acceleration

### ISSUE THREAD

**Issue by favu100** [Farama-Foundation/HighwayEnv#498]
Hey,

As stated in https://highway-env.farama.org/actions/, it seems that the AI’s minimum deceleration and maximum acceleration are -5 m/s^2. and 5 m/s^2. respectively. Do these values correspond to the EgoVehicle although we use the discrete action space? Or are there any other values we have to take into account?

Best regards,

Fabian

**Comment by eleurent** [comment]
The Discrete action space can be configured with an acceleration_range=(min, max) parameter. But yes, if None is provided, then the range of (-5, 5) is also used by default (like for ContinuousAction)

**Comment by favu100** [comment]
Thank you!
