### ISSUE TITLE
I would like to ask about the possibility of introducing signal control at intersections

### ISSUE THREAD

**Issue by yshichseu** [Farama-Foundation/HighwayEnv#506]
Thank you for your contribution to the autonomous driving traffic scenario. As a beginner in reinforcement learning, due to my research needs, I hope to introduce signals for control in intersection scenes. May I ask if this change is possible? Can you give me a train of thought? Thank you very much!

**Comment by eleurent** [comment]
> May I ask if this change is possible? 

Sorry, I am only maintaining the current set of features, and I do not plan on making any addition at the moment.
That being said, PRs are more than welcome so feel free to try!

> Can you give me a train of thought? Thank you very much!

As of now, there is a very (very) rudimentary implementation of traffic regulation which is only implemented in the intersection env. It is an unsignalised intersection, but you can define one of the roads (horizontal or vertical) has having priority, and all vehicles on a non-priority road will yield to priority vehicles (i.e. if they detect a risk of collisions in the next 2s, they set their target speed to 0, while the priority vehicle keeps going).

This is implemented in https://github.com/Farama-Foundation/HighwayEnv/blob/master/highway_env/road/regulation.py

You may edit this and/or the environment to:
- switch which lane has a traffic light on, based on simulation time (env.time).
- apply the yield (set target speed to 0) not only when there is an imminent collision, but whenever the vehicle is approaching the end of the road.

**Comment by eleurent** [comment]
EDIT: a simpler implementation could actually be to add/remove invisible Obstacles (https://github.com/Farama-Foundation/HighwayEnv/blob/master/highway_env/vehicle/objects.py#L181) at the end of the lanes where there are red traffic lights. The incoming vehicles should automatically slow down and stop before these obstacles. And then whenever the light turns green, you can delete the obstacle from the scene.

**Comment by yshichseu** [comment]
Thank you for your attention and suggestions. I think this should be a simple and feasible solution. Thank you again!

> EDIT: a simpler implementation could actually be to add/remove invisible Obstacles (https://github.com/Farama-Foundation/HighwayEnv/blob/master/highway_env/vehicle/objects.py#L181) at the end of the lanes where there are red traffic lights. The incoming vehicles should automatically slow down and stop before these obstacles. And then whenever the light turns green, you can delete the obstacle from the scene.
