### ISSUE TITLE
Observation item reverse of surronding vehicles

### ISSUE THREAD

**Issue by Samisang** [Farama-Foundation/HighwayEnv#508]
Dear authors:  
   Thanks for implementation and maintenance of the awesome project! Recently I customize(modifications about road parameters) a single-agent enviroment based on envs/merge_env.py. The **_key configurations_** are listed below:
```python
            "observation": {
                "type": "Kinematics",
                "vehicles_count": 5,    # the default value(rows of observation)
                "features": ["presence","x","y","vx","vy"],
                "normalize": False,
                "absolute": True,
                "order": "sorted",
                "see_behind": True
            },
``` 
  It comfuses me that when I try to access the **`Observation array`** in test phase, everything goes fine till the ego vehicle enters the merging area. Some of the **Obtained observation** data are presented in the following pic:
![problem](https://github.com/Farama-Foundation/HighwayEnv/assets/63208373/138f709e-0cb7-4e37-b082-91e2b31f9499)
  We can see 3 vehicles' presence in array, with the ego vehicle's observation always fixed in the first row according to the docs, but leaving the location of rest 2 vehicles' observation item uncertain(forgive me if my expression is not accurate). I wonder if there is **any feasible configuration specification** or **the other probable solution** to help to access these observation data in oder? Wish an early reply with anticipation!

**Comment by eleurent** [comment]
Hi,
I'm not sure what you mean by "in order".
Right now, the vehicles are sorted by increasing distance to the ego-vehicle.

In your example, there are two vehicles: one is behind (x=89 at t=0 and x=93 at t=1), and one is in front of the ego vehicle (x=144 at t=0 and x=149 at t=1)

- In the first timestep, the rear vehicle is at distance 115 - 89 = 26 and the front vehicle is at distance 144-115 = 29, so their ranks in the observation are 1 and 2 respectively. 
- But in the second timestep, the rear vehicle is now at distance  121.37 - 93.41 =27.96 and the front vehicle is at distance  149-121.37 = 27.63.
So the front vehicle just got closer, which explains why it moved up a row in the observation.

If you don't like this behaviour, you can simply disable the "order": "sorted" config and use "order": None instead, in which case the vehicles are added to observation in their order of creation in the scene.
Alternatively, you could add an `id` feature to keep track of which vehicle is which between observations

**Comment by Samisang** [comment]
Much appreciation to the timely and detailed reply! I got a bit confused of the attribute `order` when reading the docs. Thanks again for expaciating the particulars and the new feasible alternative!

**Comment by eleurent** [comment]
I think the following may be happening:

1. Env creation (env = gym.make(...)), vehicles are created with indices 0,1,2
2. Env reset (obs, info = env.reset()), the scene is cleared and new vehicles are created with indices 3,4,5. 

This could be "fixed" e.g. by resetting the MAX_ID counter during env.reset(), but I don't really think it's much of an issue.

**Comment by Samisang** [comment]
Appreciations for the insighful comment!
