### ISSUE TITLE
Path search problem for known road targets

### ISSUE THREAD

**Issue by SEUCGX** [Farama-Foundation/HighwayEnv#512]
Thanks to the author for the environment. In the process of using it, I found that even fixed the seed could not fully reproduce the results. After some time of examination, I think I have found the reason. 
In the line 137 of road.py, the author uses bfs for path search, but uses the "set" data structure, which makes it impossible to reproduce even fixed the seed.
I use a simple alternative solution.
for _next in sorted([key for key in self.graph[node].keys() if key not in path])
https://github.com/Farama-Foundation/HighwayEnv/blob/4397bbeab8ac2a5ada1a9be26c461d7e14b49199/highway_env/road/road.py#L137C1-L137C1

**Comment by eleurent** [comment]
Oh! That's a really great catch! Thanks a lot for sharing this, I'll push your fix later today.
