### ISSUE TITLE
Continuously Adding Vehicles During Runtime in Modified Roundabout Scenario

### ISSUE THREAD

**Issue by xiaofutongxuo** [Farama-Foundation/HighwayEnv#515]
Hello,

I've been working with and modifying the highway-env library, specifically the roundabout environment. During my adjustments, I noticed that the make vehicle method allows vehicles to be generated only after an environment reset. Given my modifications include a larger roundabout, and the ego vehicle's speed is set to be lower than other vehicles', the ego soon finds itself isolated after some runtime with no background vehicles around, which doesn't align with real-world scenarios.

I'd like to be able to add vehicles continuously during the simulation to ensure a realistic density of traffic around the ego vehicle at all times. Could you guide me on how to achieve this continuous addition of vehicles?

Thank you for your assistance and for the excellent work on this environment!

Best regards!

**Comment by eleurent** [comment]
Hi! You might want to take a look at the intersection environment where I am doing similar: 

https://github.com/Farama-Foundation/HighwayEnv/blob/6566b518076f6d3022648898833364825494bc32/highway_env/envs/intersection_env.py#L122

in the environment.step method, I am calling a `_spawn_vehicles` method that randomly creates a vehicle incoming in the intersection, and a `_clear_vehicles` method that removes environments from the scene (e.g. when they leave the scene, or could be when they are too far away from the ego vehicle)
