### ISSUE TITLE
About Single Agent and Multi-Agent

### ISSUE THREAD

**Issue by AntaiXie** [Farama-Foundation/HighwayEnv#516]
Hello,

I want to test every vehicle in a multi-agent environment using trained models from a single agent environment. Can this be achieved? If the action space of these single agents is different, can it be achieved?

Thank you for your assistance and for the excellent work on this environment!

Best regards!

**Comment by eleurent** [comment]
Hi,

> I want to test every vehicle in a multi-agent environment using trained models from a single agent environment. Can this be achieved?

Yes, in the [multi-agent setting](https://highway-env.farama.org/multi_agent/) the environment returns a tuple of observations and takes in a tuple of action. So you can use your separately-trained single-agent to compute an action for each observation in the tuple, and step the env with the tuple of resulting actions. Something like
```
obs, info = env.reset()
action = (pretrained_agent.act(observation) for observation in obs)
env.step(action)
```

> If the action space of these single agents is different, can it be achieved?

Right now it wouldn't work as the `MultiAgentAction` action space is built by copying a single shared action space N times. But it would be very easy to adapt it to load N distinct action spaces, just edit this line: 
https://github.com/Farama-Foundation/HighwayEnv/blob/6566b518076f6d3022648898833364825494bc32/highway_env/envs/common/action.py#L281


That would not work with a single pretrained agent though, you would need to pretrain one agent per action space.

**Comment by AntaiXie** [comment]
In a multi-agent environment, is the observation space multiple observations centered around each agent (like the observation space of a single agent, multiple)? 

Additionally, I have a question about whether it is possible to provide an independent observation space for vehicles other than EGO vehicles in a single agent environment. Due to the control of other vehicles, I would like to use the status information of the surrounding vehicles as input. I want to know how to modify it to achieve it.

**Comment by AntaiXie** [comment]
![1697088074167](https://github.com/Farama-Foundation/HighwayEnv/assets/117359479/610b3410-c02e-41b1-abf2-3ba8db233960)
I would like to know if other vehicles can also obtain the location information of vehicles in this lane and left and right lanes within a certain range. Should we determine the vehicle numbers within the range and then read self.vehicle1/2/3 position? How do you know which vehicles are near the ones circled in the red circle?

**Comment by eleurent** [comment]
> In a multi-agent environment, is the observation space multiple observations centered around each agent (like the observation space of a single agent, multiple)?

It depends on the type of observation, but typically yes.

> Additionally, I have a question about whether it is possible to provide an independent observation space for vehicles other than EGO vehicles in a single agent environment. Due to the control of other vehicles, I would like to use the status information of the surrounding vehicles as input. I want to know how to modify it to achieve it.

This is not possible as of now, but you can take inspiration of what is done when there are multiple controlled vehicles: a new observation type is created for each vehicle, and the returned observation will be the tuple of all per-vehicle observation.
See:

https://github.com/Farama-Foundation/HighwayEnv/blob/085f8c82b4d48424cf8ab61f52f824d185b63f0e/highway_env/envs/common/observation.py#L487

**Comment by eleurent** [comment]
>  I would like to know if other vehicles can also obtain the location information of vehicles in this lane and left and right lanes within a certain range. Should we determine the vehicle numbers within the range and then read self.vehicle1/2/3 position? How do you know which vehicles are near the ones circled in the red circle?

If you are using the kinematics observation, you can use the sorted option to ensure vehicles are sorted by distance to the observer vehicle. 
But this won't be exactly what you want, which requires defining a new observation type, iterating over all vehicles, checking if they are in the observer vehicle's lane or left/right lane, and within the range (or e.g. within a rectangle centered on the vehicle), etc.
