### ISSUE TITLE
Solving some errors and ambiguities

### ISSUE THREAD

**Issue by HodaHo** [Farama-Foundation/HighwayEnv#522]
Dear author;
I have some errors and ambiguities in the run of the codes and the examples, please guide me: (2 parts)

1- I'd like to run and test the following examples on Google Colab, but I am faced with the below errors, what's the reason?
For example:   Highway with SB3's DQN            or      Intersection with DQN and social attention

- error:
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-1-d7df0fa2f72e>](https://localhost:8080/#) in <cell line: 19>()
     17 get_ipython().system('git clone https://github.com/eleurent/highway-env.git 2> /dev/null')
     18 sys.path.insert(0, '/content/highway-env/scripts/')
---> 19 from utils import show_videos

6 frames
[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)
   1861                     if errno_num != 0:
   1862                         err_msg = os.strerror(errno_num)
-> 1863                     raise child_exception_type(errno_num, err_msg, err_filename)
   1864                 raise child_exception_type(err_msg)
   1865 

FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb'

----------------------------------------------------------------------------------------------------
2- what is the meaning and concept of the following cases in the configuration of the environment?

- 'centering_position': [0.3, 0.5],
 
 - 'ego_spacing': 2,
 
- 'scaling': 5.5,

- 'vehicles_density': 1

---------------------------------------------------------------------------------------------------

Best regards

**Comment by mehmetozturan** [comment]
Hi, for problem-1; try to separate the `xvfb python-opengl ffmpeg` installations. I changed this part (Visualization utils) so it worked for me:
```
# Visualization utils
%load_ext tensorboard
import sys
from tqdm.notebook import trange
!pip install tensorboardx gym pyvirtualdisplay
# !apt-get install -y xvfb python-opengl ffmpeg
!apt-get install  xvfb
!apt-get install python-opengl ffmpeg'
!git clone https://github.com/eleurent/highway-env.git 2> /dev/null
sys.path.insert(0, '/content/highway-env/scripts/')
from utils import record_videos, show_videos
```

**Comment by eleurent** [comment]
Thanks for the feedback, I could reproduce your problem-1 on colab. 
Looks like pyvirtualdisplay needs Xvfb to be installed, but the apt-get installation was failing because of python-opengl somehow. I removed it from installed packages, looks like its not needed anymore.

> 2- what is the meaning and concept of the following cases in the configuration of the environment?

>    'centering_position': [0.3, 0.5],

>    'ego_spacing': 2,

>    'scaling': 5.5,

>    'vehicles_density': 1

- centering_position is the screen position (here 30% width and 50% height) of the object that the camera is locked on to.
- ego_spacing control how much space there is between the controlled vehicle and the next vehicle on the road (shouldn't be too small to prevent unavoidable early collisions, e.g. the front vehicle speed is random and could be too low for the ego-vehicle to avoid if it spawns right behind)
- scaling: the zoom level of the camera
- vehicles_density: how close vehicle are created to one another

**Comment by HodaHo** [comment]
Thank you for your reply,
For problem1, I tried to separate xvfb python-opengl ffmpeg installations due to mehmet ozturan suggestion blow my question and it worked correctly for me. But after your changes, the code does not execute and the following error is displayed :

- error:

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-1-b6828c17c31e>](https://localhost:8080/#) in <cell line: 21>()
     19 get_ipython().system('git clone https://github.com/Farama-Foundation/HighwayEnv.git 2> /dev/null')
     20 sys.path.insert(0, '/content/highway-env/scripts/')
---> 21 from utils import record_videos, show_videos

ModuleNotFoundError: No module named 'utils'


It should be noted that  mehmet ozturan suggestion does not work anymore. please consider it.

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by eleurent** [comment]
You should check whether the git clone was successful, and also the sys.path.insert.
The failing command is trying to import the utils.py file, which is here: https://github.com/Farama-Foundation/HighwayEnv/blob/master/scripts/utils.py

**Comment by zlite** [comment]
These still fail for me in the same way on Collab

**Comment by eleurent** [comment]
This should be fixed now, let me know if you still have any issue.

P.S.: You're Chris Anderson! 😮 humbled to see you here

**Comment by zlite** [comment]
Thanks! Antonin sent me. I'm impressed!

**Comment by HodaHo** [comment]
Thanks for the previous corrections, it works correctly.

Please check the (Training a DQN with social attention on intersection-v0) example (https://colab.research.google.com/github/eleurent/highway-env/blob/master/scripts/intersection_social_dqn.ipynb)

Currently, it also gives an error in the (Prepare environment, agent, and evaluation process) section

**Comment by eleurent** [comment]
Thanks for the feedback HodaHo, I could reproduce the issue and it should be fixed now.

**Comment by HodaHo** [comment]
Thank you. it is working correctly now. 
Have these debuggings been made in codes for use in Anaconda (not Colb), too?

**Comment by eleurent** [comment]
>  Have these debuggings been done in codes for use in Anaconda (not Colab), too?

You can use the .py files in the scripts folder. 
Or you can adapt the colab notebooks to python scripts by removing the visualisation code (imports and calls to record_videos, show_videos, which are all a bit colab-specific).

**Comment by izvvv** [comment]
> > Have these debuggings been done in codes for use in Anaconda (not Colab), too?
> 
> You can use the .py files in the scripts folder. Or you can adapt the colab notebooks to python scripts by removing the visualisation code (imports and calls to record_videos, show_videos, which are all a bit colab-specific).

我在win端Anacona中不使用utils.py文件，通过pygame库图片流代替视频流显示，它是能够成功的。但是我想要实现视频可视化显示停车过程应该如何做？我尝试过：
在执行”from utils import record_videos, show_videos“时出现“FileNotFoundError: [WinError 2] 系统找不到指定的文件。”的错误，具体如下：
Cell In[1], line 8
      6 import  sys
      7 from tqdm.notebook import trange
----> 8 from utils import record_videos, show_videos
      9 get_ipython().run_line_magic('matplotlib', 'inline')

File F:\1\env\utils.py:8
      5 from IPython import display as ipythondisplay
      6 from pyvirtualdisplay import Display
----> 8 display = Display(visible=0, size=(1400, 900))
      9 display.start()
     12 def record_videos(env, video_folder="videos"):

File E:\Anaconda\envs\2\Lib\site-packages\pyvirtualdisplay\display.py:54, in Display.__init__(self, backend, visible, size, color_depth, bgcolor, use_xauth, retries, extra_args, manage_global_env, **kwargs)
     51 if not cls:
     52     raise ValueError("unknown backend: %s" % self._backend)
---> 54 self._obj = cls(
     55     size=size,
     56     color_depth=color_depth,
     57     bgcolor=bgcolor,
     58     retries=retries,
     59     use_xauth=use_xauth,
     60     # check_startup=check_startup,
     61     extra_args=extra_args,
     62     manage_global_env=manage_global_env,
     63     **kwargs
     64 )

File E:\Anaconda\envs\2\Lib\site-packages\pyvirtualdisplay\xvfb.py:44, in XvfbDisplay.__init__(self, size, color_depth, bgcolor, use_xauth, fbdir, dpi, retries, extra_args, manage_global_env)
     41 self._fbdir = fbdir
     42 self._dpi = dpi
---> 44 AbstractDisplay.__init__(
     45     self,
     46     PROGRAM,
     47     use_xauth=use_xauth,
     48     retries=retries,
     49     extra_args=extra_args,
     50     manage_global_env=manage_global_env,
     51 )

File E:\Anaconda\envs\2\Lib\site-packages\pyvirtualdisplay\abstractdisplay.py:85, in AbstractDisplay.__init__(self, program, use_xauth, retries, extra_args, manage_global_env)
     82 self._pipe_wfd = None
     83 self._retries_current = 0
---> 85 helptext = get_helptext(program)
     86 self._has_displayfd = "-displayfd" in helptext
     87 if not self._has_displayfd:

File E:\Anaconda\envs\2\Lib\site-packages\pyvirtualdisplay\util.py:13, in get_helptext(program)
      6 cmd = [program, "-help"]
      8 # py3.7+
      9 # p = subprocess.run(cmd, capture_output=True)
     10 # stderr = p.stderr
     11 
     12 # py3.6 also
---> 13 p = subprocess.Popen(
     14     cmd,
     15     stdout=subprocess.PIPE,
     16     stderr=subprocess.PIPE,
     17     shell=False,
     18 )
     19 _, stderr = p.communicate()
     21 helptext = stderr.decode("utf-8", "ignore")

File E:\Anaconda\envs\2\Lib\subprocess.py:1026, in Popen.__init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask, pipesize, process_group)
   1022         if self.text_mode:
   1023             self.stderr = io.TextIOWrapper(self.stderr,
   1024                     encoding=encoding, errors=errors)
-> 1026     self._execute_child(args, executable, preexec_fn, close_fds,
   1027                         pass_fds, cwd, env,
   1028                         startupinfo, creationflags, shell,
   1029                         p2cread, p2cwrite,
   1030                         c2pread, c2pwrite,
   1031                         errread, errwrite,
   1032                         restore_signals,
   1033                         gid, gids, uid, umask,
   1034                         start_new_session, process_group)
   1035 except:
   1036     # Cleanup if the child failed starting.
   1037     for f in filter(None, (self.stdin, self.stdout, self.stderr)):

File E:\Anaconda\envs\2\Lib\subprocess.py:1538, in Popen._execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_gid, unused_gids, unused_uid, unused_umask, unused_start_new_session, unused_process_group)
   1536 # Start the process
   1537 try:
-> 1538     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1539                              # no special security
   1540                              None, None,
   1541                              int(not close_fds),
   1542                              creationflags,
   1543                              env,
   1544                              cwd,
   1545                              startupinfo)
   1546 finally:
   1547     # Child is launched. Close the parent's copy of those pipe
   1548     # handles that only the child should have open.  You need
   (...)
   1551     # pipe will not close when the child process exits and the
   1552     # ReadFile will hang.
   1553     self._close_pipe_fds(p2cread, p2cwrite,
   1554                          c2pread, c2pwrite,
   1555                          errread, errwrite)

**Comment by eleurent** [comment]
>  ----> 8 from utils import record_videos, show_videos

Like I said, you should remove this code, as it uses pyvirtualdisplay / Xvfb which is only required for colab (which dont have a display), so it will fail if you try to run it on a local computer with a screen. Juste remove all the visualisation code of the colab.
