### ISSUE TITLE
About IDM

### ISSUE THREAD

**Issue by AntaiXie** [Farama-Foundation/HighwayEnv#523]
How to achieve the simultaneous existence of AggressiveVehicle and DefensiveVehicle as shown in the picture?
![图片1](https://github.com/Farama-Foundation/HighwayEnv/assets/117359479/d285521d-629c-49e4-912b-1557f578e234)

Class AggressiveVehicle (LinearVehicle):

LANE_ CHANGE_ MIN_ ACC_ GAIN=1.0 # [m/s2]

MERGE_ ACC_ GAIN=0.8

MERGE_ VEL_ RATIO=0.75

MERGE_ TARGET_ VEL=30

ACCESSION_ PARAMETRS=[MERGE-ACC_GAIN/(1- MERGE-VEL-RATIO) * MERGE-TARGET_VEL),

MERGE_ ACC_ GAIN/(MERGE-VEL_RATIO * MERGE-TARGET_VEL),

0.5]

Class DefensiveVehicle (LinearVehicle):

LANE_ CHANGE_ MIN_ ACC_ GAIN=1.0 # [m/s2]

MERGE_ ACC_ GAIN=1.2

MERGE_ VEL_ RATIO=0.75

MERGE_ TARGET_ VEL=30

ACCESSION_ PARAMETRS=[MERGE-ACC_GAIN/(1- MERGE-VEL-RATIO) * MERGE-TARGET_VEL),

MERGE_ ACC_ GAIN/(MERGE-VEL_RATIO * MERGE-TARGET_VEL),

2.0]

I saw only other in config_ Vehicle_ Type: IDM. Also, I would like to ask if there is a simple way to achieve random changes in the parameters of IDM during the training process, that is, to continuously switch between different modes of AggregativeVehicle and DefensiveVehicle

**Comment by eleurent** [comment]
> How to achieve the simultaneous existence of AggressiveVehicle and DefensiveVehicle as shown in the picture?
> Also, I would like to ask if there is a simple way to achieve random changes in the parameters of IDM during the training process, that is, to continuously switch between different modes of AggregativeVehicle and DefensiveVehicle


The best is probably to edit the environment's _create_vehicles() method and manually add different vehicles of different types. Agressive/Defensive are just presets of parameters, so you can also continuously switch by setting these configs to random values when creating a vehicle.
