### ISSUE TITLE
speed_limit usage in the RoadNetwork

### ISSUE THREAD

**Issue by Fengtao22** [Farama-Foundation/HighwayEnv#524]
Hi, I was wondering what is the usage of the speed_limit in the straight_road_network method. I did not see any reward related with this speed limitation. Could anyone explain it? Thanks!

**Comment by Fengtao22** [comment]
Update: It seems that the speed_limit is used as one potential source for defining the initial speed of a vehicle (for highway-v0 task).

**Comment by eleurent** [comment]
Yes, that's correct. Another use case is regulated_intersection, where priority rules apply and some vehicles yield to others. When a vehicle yields, it's target_speed is set to 0. When the intersection is clear again, the vehicle restarts by setting its target_speed to the lane's speed_limit.
