### ISSUE TITLE
QUestion about observation_factory 

### ISSUE THREAD

**Issue by SeasonedLeo** [Farama-Foundation/HighwayEnv#526]
Hello @eleurent  

First of all thanks for making it available for us to use and helping with questions . 

I was wondering if there is a way to observed more than 1 type of observations . for ex in the code below we can choose only 1 at a given time. I want to include two types of observation , do I have to write a seprate class for that or there is way I can include more than 1 type of observation .

Thanks for your help !!!!

![image](https://github.com/Farama-Foundation/HighwayEnv/assets/71835881/94094507-4bf0-44e1-b876-cf06aae806a8)

**Comment by eleurent** [comment]
Yes, you can use the TupleObservation, which is constructed with a tuple of ObservationType configurations, and returns the corresponding tuple of observations.
