### ISSUE TITLE
Config parameter "action_reward"

### ISSUE THREAD

**Issue by Yigit-Kuyu** [Farama-Foundation/HighwayEnv#527]
Hello,

I searched for the definition of "action_reward" parameter on the official website and in the issues, but I have not found any proper information. What does "action_reward" parameter mean? and why it generally take "-0.3" in the given examples?

Thanks in advance

**Comment by myildirimm** [comment]
Hello Yigit,
In RL, sometimes a minor penalty is given to an action to prevent agent to perform unnecessary actions. It is kind of a cost to prevent undesired random actions.

**Comment by Yigit-Kuyu** [comment]
Thank you for your clarification.
