### ISSUE TITLE
Render image with recent history

### ISSUE THREAD

**Issue by wangyixu14** [Farama-Foundation/HighwayEnv#529]
Hi there,

Thanks for the effort in developing this wonderful tool.
A question I have is whether is there a way to render images for the ego and surroundings with recent trajectory history plotted. I am looking for something like 
<img width="427" alt="ab95bc9567cc3211a39bf53c43123b4" src="https://github.com/Farama-Foundation/HighwayEnv/assets/34372413/51ab8bc7-69a9-48f0-bcda-31bb20f59019">

**Comment by eleurent** [comment]
Hi, you simply need to configure the environment with `{'display_trajectories': True}`

gym.make(env_id, config={'display_trajectories': True})
