### ISSUE TITLE
How to modify the MOBIL lane change time

### ISSUE THREAD

**Issue by AntaiXie** [Farama-Foundation/HighwayEnv#530]
Dear author, thank you for your previous guidance, which has helped me solve a lot of problems.I would like to ask how to modify the MOBIL lane change time? Is it fixed within how many “dt” to complete?

**Comment by eleurent** [comment]
The lane change duration is given by the response time of the vehicles' steering controller. You can affect it by changing the value of `TAU_LATERAL` (and maybe `TAU_HEADING` if you get some instabilities) in 
https://github.com/Farama-Foundation/HighwayEnv/blob/8d9324092064ca955df8c3b27a8f1498e14f8624/highway_env/vehicle/controller.py#L24
