### ISSUE TITLE
OccupancyGridObservation

### ISSUE THREAD

**Issue by vlongle** [Farama-Foundation/HighwayEnv#541]
Hello,

Thank you for making this awesome environment! Currently, the following code
```
env = ParkingEnv(render_mode='rgb_array')

grid_step = 5
agent_view_size = 40
grid_size = agent_view_size*grid_step
config = {"observation": {
    "type": "OccupancyGrid",
    "absolute": False,
    "grid_step": [grid_step, grid_step],
    "grid_size": [[-grid_size//4, grid_size//4], [-grid_size, grid_size]],
},
}
env.configure(config)

obs, info = env.reset(seed=0)
presence = obs[0]
print(np.nonzero(presence))
```
that has the grid's width four times as big as the height to match the screen_height: width aspect ratio in the render function is returning an empty array when I was expecting the vehicle in the middle.

**Comment by eleurent** [comment]
Thanks a lot for the feedback, that was indeed a bug! It should be fixed now.
