### ISSUE TITLE
Add random obstables to parking-env

### ISSUE THREAD

**Issue by moneypi** [Farama-Foundation/HighwayEnv#559]
![飞书20240117-105531 00_00_03--00_00_19](https://github.com/Farama-Foundation/HighwayEnv/assets/27052490/c5e69c6b-927f-4298-b306-865a59f04909)
If I add some random obstacles, how to modify code to get the best result?
Can anybody help me?

**Comment by eleurent** [comment]
Hi! What do you mean by "get the best result" exactly?

**Comment by moneypi** [comment]
> Hi! What do you mean by "get the best result" exactly?

Hi, I wish the vehicle can park in expected position without collision.

**Comment by moneypi** [comment]
I create a new issue in https://github.com/Farama-Foundation/HighwayEnv/issues/570 , so I close this one.
