### ISSUE TITLE
Vehicle heading angle

### ISSUE THREAD

**Issue by izvvv** [Farama-Foundation/HighwayEnv#587]
How do I change the heading angle of a parked vehicle? I need to keep the vehicle level.

![image](https://github.com/Farama-Foundation/HighwayEnv/assets/78134574/40762fa8-65f6-4059-9660-3dc33f29a786)
![image](https://github.com/Farama-Foundation/HighwayEnv/assets/78134574/33474440-3dc9-4ab6-bc22-5e431f7960a8)

**Comment by izvvv** [comment]
And I've already added PI/2 to my goal
![image](https://github.com/Farama-Foundation/HighwayEnv/assets/78134574/b3d0bb8a-8271-4034-bae7-64cd63ffaabb)

**Comment by eleurent** [comment]
`v = Vehicle.make_on_lane(...)` aligns the vehicle heading with the lane direction, by default.
you can just add the following line below to rotate the vehicles:

```
v = Vehicle.make_on_lane(...)
v.heading += np.pi / 2
v.color = ...
```
