### ISSUE TITLE
Randint problem when loading racetrack environment

### ISSUE THREAD

**Issue by Agathe48** [Farama-Foundation/HighwayEnv#588]
I notice there was sometimes a bug when loading the racetrack environment, the following error was shown: 
File highway_env\road\road.py", line 254, in random_lane_index
    _id = np_random.randint(len(self.graph[_from][_to]))
AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'

I managed to fix it in my local environment by changing this line in the file: highway_env\road\road.py", line 254, in random_lane_index
I change the line `_id = np_random.randint(len(self.graph[_from][_to]))` to `_id = np_random.integers(len(self.graph[_from][_to]))`.

I don't know if it's the best way to fix this bug but it works for me.

**Comment by eleurent** [comment]
Hi @Agathe48,
Sorry about this, this has been fixed already in 

https://github.com/Farama-Foundation/HighwayEnv/commit/b0a4a847b70e60fc6e00f746ce325d7f869c3a9e

(and yes you suggested the correct fix)

But it hasn't made it into a release yet, I guess I should probably make a hot fix
