### ISSUE TITLE
the Collision Problem of Multiple Control Vehicles(mutil-agent)

### ISSUE THREAD

**Issue by HaoChenga** [Farama-Foundation/HighwayEnv#605]
Hello, thank you for your excellent work.
When testing on multiple agents, I encountered a problem with multi-control vehicle collision detection. Regarding the collision of a single vehicle, I can check whether there is a collision from the `info['crashed']` returned by `env. step()`, but when the action contains multiple vehicles, the info value returned is still for a single vehicle, so how can I get the collision information of other controlled vehicles? Looking forward to your reply~ @eleurent

**Comment by SEUCGX** [comment]
The definition of collision needs to be modified. In the default environment, the definition of reward and collision is only derived from the first car.

**Comment by HaoChenga** [comment]
Thank you for your reply. I have already written the code for the vehicle collision and have now closed the issue.
