### ISSUE TITLE
How to get the Longitudinal speed, Lateral speed, and steering angle of a vehicle?

### ISSUE THREAD

**Issue by Rza-A** [Farama-Foundation/HighwayEnv#606]
Hello, 
This question may come across as basic, but I'd like to know how can I get the longitudinal speed, lateral speed, and steering angle of a vehicle. I used the dir(vehicle) statement but I couldn't find these parameters. 

I'd appreciate any help.

**Comment by seominseokt** [comment]
Check out the document at [carla.Vehicle](https://carla.readthedocs.io/en/0.9.15/python_api/#carlavehicle).

**Comment by seominseokt** [comment]
Check out the document at [Kinematics](https://highway-env.farama.org/observations/#kinematics)

**Comment by hkbharath** [comment]
You can use `vehicle.to_dict()`.
