### ISSUE TITLE
Customize the vehicle location

### ISSUE THREAD

**Issue by Captain6606** [Farama-Foundation/HighwayEnv#607]
Hello,
    I want to know if I can fix the initial position and speed of the car in the Highway scenario.
Looking forward to your reply.

**Comment by hkbharath** [comment]
Yes, you can extend the existing environment class and override the [`_create_vehicle`](https://github.com/Farama-Foundation/HighwayEnv/blob/251e804926a5ffd73e31ec3a0509c52e72d6b0dd/highway_env/envs/highway_env.py#L68) function to create vehicles in specific initial position and speed.
