### ISSUE TITLE
AttributeError: module 'highway_env.__init__' has no attribute 'register_highway_envs

### ISSUE THREAD

**Issue by erfun77** [Farama-Foundation/HighwayEnv#630]
Hi,
I downloaded the last version of highway_env from GitHub on my new PC. I got an error regarding highway_env registration: " AttributeError: module 'highway_env.__init__' has no attribute 'register_highway_envs.' I tried previous versions, and they worked fine. It seems a change might have been made 28 days ago that could be causing this issue. 

Edouard's answer:
Hi, the ' register_highway_envs ' method you are trying to call is [here](https://github.com/Farama-Foundation/HighwayEnv/blob/def6f4fe9068cc0136fd846b42def700bc9b664c/highway_env/__init__.py#L22), it has been renamed with a leading '_' to signal that you should no longer have to call it yourself, you should just `import highway_env` which will automatically [run env registration](https://github.com/Farama-Foundation/HighwayEnv/blob/def6f4fe9068cc0136fd846b42def700bc9b664c/highway_env/__init__.py#L122).

Tests are currently passing, so things should be fine I think, and I suspect there is a version conflict in your local setup: have you tried uninstalling the previous version? if you had previous script that were calling highway_env.register_highway_env() manually, you can just remove this line now.

**Comment by erfun77** [comment]
Does it make help?
 from gymnasium.envs.registration import (
  File "C:\Users\umroot\AppData\Local\Programs\Python\Python37\lib\site-packages\gymnasium\envs\__init__.py", line 382, in <module>
    load_plugin_envs()
  File "C:\Users\umroot\AppData\Local\Programs\Python\Python37\lib\site-packages\gymnasium\envs\registration.py", line 600, in load_plugin_envs
    fn = plugin.load()
  File "C:\Users\umroot\AppData\Local\Programs\Python\Python37\lib\site-packages\importlib_metadata\__init__.py", line 211, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'highway_env.__init__' has no attribute 'register_highway_envs'

**Comment by eleurent** [comment]
Ok this is strange, can you also share what script you are running?

**Comment by erfun77** [comment]
It's odd because in my laptop by importing highway_env the problem solved. But in the other PC, I couldn't solve the issue. Thanks!

**Comment by eleurent** [comment]
Ok, I think it might be some remains of an old version / script in your other PC. `register_highway_envs` no longer exists (without a leading _) and no code should try to call it. So this can probably be solved by uninstalling the existing package / starting fresh.

I'll close this for now, but feel free to reopen if anything comes up.
